[package]
name = "terustry"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
actix-web = { version = "3", features=["openssl"]}
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.21"
log = "0.4.14"
handlebars = "4.1.3"
async-recursion = "0.3.2"